sudo: required
language: generic
services: 
  - docker

before_install:
  - docker build -t pyteror/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true pyteror/docker-react npm run test -- --coverage